# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  user-service:
    build:
      context: .
      target: final
    ports:
      - 8500:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=myapp;user=root;password=Dijar2711#
    depends_on:
      - db
    networks:
      - shared-network
      - user-network 
  db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: Dijar2711#
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user-network 


networks:
    shared-network:
      external: true 
    user-network:
      driver: bridge